{
 "title": "mytest",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "History of Alert",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current State Alert",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "My Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}